[package]
name = "yan"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.0-rc0"
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git" }



[[target.starknet-contract]]
sierra = true